name: Python application

on:
  push:
    branches: [ main, python-api-dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install flake8
        pip install pytest
        pip install PythonAPI/
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./PythonAPI/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./PythonAPI/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --pyargs RIF

